upload_max_filesize = 256M
post_max_size = 260M
max_execution_time = 300
max_input_time = 300
memory_limit = 512M

extension_dir = "ext"

extension=pdo_sqlite
extension=sqlite3
extension=gd
extension=zip
extension=curl
extension=mbstring
extension=xml
extension=fileinfo
extension=openssl
